system:
  port: 4567
  debug: true
  staticpath: static
  urlpathprefix: /api/v1

db:
  # host: 192.168.18.45
  # port: 5432
  # hostname: janx-admin
  # password: 3tYapHD3aQAzCEmm
  # database: janx-admin
  host: 192.168.217.129
  port: 5432
  hostname: root
  password: pg123456
  database: janx-admin
  # 最大连接数
  maxopenconns: 25
  # 最大空闲连接
  maxidleconns: 5
  # 连接超时（秒）
  connmaxlifetime: 5
  logstatus: true
  loglevel: info

log:
  level: info
  path: log
  maxsize: 100
  maxage: 10
  maxbackups: 10
  compress: true

# jwt配置
jwt:
  # jwt标识
  realm: janx admin
  # 服务端密钥
  key: secret key
  # token过期时间, 小时
  timeout: 12
  # 刷新token最大过期时间, 小时
  max-refresh: 12

# casbin配置
casbin:
  # 模型配置文件, config.yml相对路径
  model-path: 'rbac_model.conf'

